services:
  api:
    image: ${IMAGE_URL}
    environment:
      - ASPNETCORE_ENVIRONMENT_OVERRIDE=${ASPNETCORE_ENVIRONMENT:-}
      - STUDENT_NAME=${STUDENT_NAME}
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
